### ISSUE TITLE
Private resolver functions are silently ignored

### ISSUE THREAD

**Issue by dewetblomerus** [carsdotcom/pacer#13]
While building my first Pacer workflow, I created private resolver functions in the same module as the graph.

There was no error, but the private resolver functions were not called.

I think two things should happen:

1. If private resolver functions are not supported, we should add that to the docs (I can add that if I can get confirmation that it is intentionally not supported).

2. If a `field` has a resolver function defined and it is not found, we should raise an error, ideally at compile time if feasible.

**Comment by dewetblomerus** [comment]
After working with Pacer a bit, I keep running into this. I now have my resolver functions in a separate module, but if I miss spell one or get a function clause error while calling a resolver function, Pacer quietly resolves it to `nil` with no error.

**Comment by zkayser** [comment]
Absolutely. One of the cornerstones of the way we designed Pacer was to catch a lot of these kind of things with compile-time checks. This feels like one we are missing. We can certainly improve on this experience, capturing mis-spellings and non-existent function references at compile-time, and then providing better feedback to the user if a resolver gets passed unexpected inputs, etc., at runtime.

**Comment by dewetblomerus** [comment]
I just found that if I want to reproduce this, it helps if I also forget to add dependencies for a resolver.

**Comment by zkayser** [comment]
I just opened a PR here https://github.com/carsdotcom/pacer/pull/16 to address one aspect of this issue.

**Comment by zkayser** [comment]
One aspect of this has been addressed in #16. 

We've captured another work item internally to add support for a debug mode as well.
