### ISSUE TITLE
Setting the value for fields without dependencies

### ISSUE THREAD

**Issue by vorce** [carsdotcom/pacer#7]
Hi, thanks for an interesting project!

I'm trying to understand how to set the value for a field that has no dependencies.

Let's take the `UserAdsWorkflow` graph from [the docs](https://hexdocs.pm/pacer/Pacer.Workflow.html#module-motivations) as an example, which defines a `:users` field without deps. It will be set to %FieldNotSet{} when the graph is constructed. But how would I update it to whatever I need during runtime, before executing the graph, for example based on a database call or something? Feels like I'm missing something :)

Edit: I was kind of expecting a resolver to run also for fields without dependencies, but first in the evaluation order I guess. 🤔 

Thanks again folks.

**Comment by zkayser** [comment]
Hey @vorce , glad you got this resolved 👍 

Your solution using the struct directly is more or less exactly what we do too. I will add a section to the docs that gives a few options for setting dependency-less fields to clear up the confusion.

What we generally do is either use the struct directly, or we create a regular function in the workflow module that can set required fields with no dependencies. 

It might be something like:

```elixir
defmodule MyWorkflow do
  use Pacer.Workflow
  
  graph do
    field(:my_field)
  ....
  end
  
  def from_inputs(map) do
    %__MODULE__{my_field: Map.get(map, :some_field, "maybe a default value")}
  end
end
```

Then invoke the workflow like:

```elixir
# Assuming you have a variable called `map` with input values
map
|> MyWorkflow.from_inputs()
|> Pacer.Workflow.execute()
```

☝️ If you just have one field, that approach is probably unnecessary. We have been using this approach if we need to set up a struct with something like random values (i.e., UUID generation or something like that for a field) or fetch some data from a cache and run some minor operations on that data.


Our assumptions is that you will have roughly two categories of dependency-less fields:
1) Data that is already in memory and accessible (for example, if you are running a Pacer.Worklow inside of an Oban job, this would be the data you have access to from the Oban.Job's args, etc.), or
2) Data that can be generated on demand (like generating unique IDs, timestamps, etc.) 

You may also have data that you can fetch without needing any input parameters from a cache, database, or other storage engine too. I would classify these as being similar to the type of data from the second category.
